name: Build on PR

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Bun
        uses: oven-sh/setup-bun@v2
      
      - name: Install Dependencies
        run: bun i
        
      - name: Run Build
        run: bun run build
